version: '3.6'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  data-mysql:

networks:
  backend:
    external: false
    name: backend