version: "3"

services:
  openeducat11:
    image: asperitus/openeducat:11.0
    container_name: openeducat
    environment:
      - DB_PORT_5432_TCP_ADDR=${POSTGRES_HOST}
      - DB_ENV_POSTGRES_USER=${POSTGRES_USER}
      - DB_ENV_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8069:8069"
      - "8071:8071"
    depends_on:
      - "postgres96"
    networks:
      - openeducat-net

  postgres96:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - openeducat-net

volumes:
  pg-data:

networks:
  openeducat-net: