version: "3.6"

services:
  minio:
    image: minio/minio:latest
    command: minio server /data
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=ac3
      - MINIO_SECRET_KEY=secret88
    # ports:
    #   - 9000:9000
    volumes:
      - data-minio:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend=minio"
      - "traefik.docker.network=web"
      - "traefik.entrypoints=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:minio.local.m3"
      - "traefik.port=9000"

volumes:
  data-minio:

networks:
  web:
    external: false
    name: web