#
# docker network create web
# docker network create backend
#
version: '3.6'

services:
  
  # mysql:
  #   image: mysql:5.7
  #   hostname: mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: demodb
  #     MYSQL_USER: demo
  #     MYSQL_PASSWORD: password
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   labels:
  #     - traefik.enable=false
  #   networks:
  #     - backend

  # postgres:
  #   image: docker.io/postgres:10-alpine
  #   hostname: postgres
  #   # Change that password, of course!
  #   environment:
  #     - POSTGRES_USER=demo
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     # You may store the database tables in a local folder..
  #     # - ./data/schemas:/var/lib/postgresql/data
  #     - ./data/pg:/var/lib/postgresql/data
  #     # .. or store them on some high performance storage for better results
  #     # - /path/to/ssd/storage:/var/lib/postgresql/data
  #   labels:
  #     - traefik.enable=false
  #   networks:
  #     - backend

  adminer:
      image: adminer:4.7.1-standalone
      labels:
        - traefik.backend=adminer
        - "traefik.enable=true"
        - traefik.frontend.rule=Host:adminer.local.m3
        - traefik.docker.network=web
        - traefik.port=8080
      networks:
        - backend
        - web
      # depends_on:
      #   - postgres
      #   - mysql

networks:
  web:
    external: true
    name: web
  backend:
    external: true
    name: backend

#docker network create backend