version: "3"

services:
  synapse:
    image: matrixdotorg/synapse
    hostname: matrix
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=matrix.home
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - SYNAPSE_NO_TLS=yes
      - POSTGRES_DB=synapse
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=changeme
    ports:
      - 8448:8448
      - 8008:8008
    volumes:
     - synapse-data:/data:rw
     - synapse-data:/media_store:rw
     - synapse-data:/uploads:rw
    depends_on:
      - postgres
  riot:
    image: avhost/docker-matrix-riot
    hostname: riot
    restart: unless-stopped
    entrypoint:
      - "/bin/sh"
      - -ecx
      - | 
        echo "-p 8765" > /data/riot.im.conf; /start.sh
    ports:
     - 8080:8765
    volumes:
     - riot-data:/data
    depends_on:
      - synapse
  coturn:
    image: instrumentisto/coturn
    hostname: coturn
    ports:
      - "3478:3478/udp" # STUN/TURN UDP
      - "3478:3478/tcp" # STUN/TURN TCP
      - "3479:3479/udp" # STUN/TURN UDP Alt port (RFC5780 support)
      - "3479:3479/tcp" # STUN/TURN TCP Alt port (RFC5780 support)
      - "5349:5349/udp" # STUN/TURN DTLS
      - "5349:5349/tcp" # STUN/TURN TLS
      - "5350:5350/udp" # STUN/TURN DTLS Alt port (RFC5780 support)
      - "5350:5350/tcp" # STUN/TURN TLS Alt port (RFC5780 support)
      - "49152:65535/udp" # UDP media ports for TURN relay
    # environment:
    #   PORT: 3478
    #   ALT_PORT: 3479
    #   TLS_PORT: 5349
    #   TLS_ALT_PORT: 5350
    #   MIN_PORT: 49152
    #   MAX_PORT: 65535
    #   JSON_CONFIG: '{"config":["no-auth"]}'
    volumes:
     - coturn-data:/var/lib/coturn
  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=synapse
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
volumes:
  synapse-data:
  riot-data:
  coturn-data:
  postgres-data: