#
# Use hugo for developement and 
# at the same time caddy for serving the content
#
version: '3.6'

services:
  caddy:
    image: asperitus/m3:latest
    restart: always
    # ports:
    #   - "2015:2015"
    volumes:
      - "$VOLUME/hugosite:/hugosite"
    entrypoint:
      - '/dhnt/bin/caddy'
      - '-conf'
      - '/hugosite/Caddyfile'
    labels:
      - traefik.enable=true
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend=caddy"
      - "traefik.docker.network=web"
      - "traefik.entrypoints=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:www.local.m3,www.local.m3.dhnt.io"
      - "traefik.port=2015"
    networks:
      web:
  #
  hugo:
    image: asperitus/hugo:latest
    restart: always
    ports:
      - "1313:1313"
    entrypoint:
      - '/bin/hugo'
      - 'server'
      - '--bind=0.0.0.0'
      - '-D'
      - '-w'
      - 'd'
      - '/www/public'
    volumes:
      - "$VOLUME/hugosite/terrassa:/www"
    labels:
      - "traefik.enable=false"

networks:
  web:
    external: false
    name: web
##
