version: "3.6"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret88
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  data-postgres:

networks:
  backend:
    external: false
    name: backend