#
version: '3.6'

services:
  frpc:
      build:
        context: ./
        dockerfile: Dockerfile
      image: asperitus/frp:latest
      restart: always
      ports:
        - "7400:7400"
      volumes:
        - ./conf:/etc/frp
        - ./log:/var/log
      entrypoint:
        - '/bin/frpc'
        - '-c'
        - '/etc/frp/frpc.ini'

networks:
  default:
    external: true
    name: web
##