#
version: '3.6'

services:
  frps:
    build:
      context: ./
      dockerfile: Dockerfile
    image: asperitus/frp:latest
    restart: always
    volumes:
      - ./conf:/etc/frp
      - ./log:/var/log
    ports:
      - "7000:7000"
      - "7500:7500" 
      - "80:80"
      - "443:443"
    entrypoint:
      - '/bin/frps'
      - '-c'
      - '/etc/frp/frps.ini'
##