#https://github.com/ipfs/go-ipfs/blob/master/Dockerfile

version: "3.6"

services:
  #
  ipfs:
    image: ipfs/go-ipfs:latest
    hostname: ipfs
    ports:
      # Swarm TCP; should be exposed to the public
      - "4001:4001"
      # Daemon API; must not be exposed publicly but to client services under you control
      # - "5001:5001"
      # Web Gateway; can be exposed publicly with a proxy, e.g. as https://ipfs.example.org
      # - "8080:8080"
      # Swarm Websockets; must be exposed publicly when the node is listening using the websocket transport (/ipX/.../tcp/8081/ws).
      # - "8081:8081"

    volumes:
      - data-ipfs:/data/ipfs

networks:
  web:
    external: false
    name: web

volumes:
  data-ipfs: