version: "3.6"

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8088:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - web

networks:
  backend:
    external: false
    name: backend
  web:
    external: false
    name: web