
version: "3.6"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - web

networks:
  backend:
    external: false
    name: backend
  web:
    external: false
    name: web